#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════════════
# Blue/Green Deployment Script
# ═══════════════════════════════════════════════════════════════════════════════
# Usage: ./scripts/deploy-bluegreen.sh <image-digest>
# Example: ./scripts/deploy-bluegreen.sh sha256:abc123...
#
# Flow:
#   1. Read current active color from .bluegreen.state
#   2. Determine target color (the opposite of active)
#   3. Pull and start target container with new digest
#   4. Run health checks on target (retry with backoff)
#   5. If healthy → rewrite nginx/active.conf → reload nginx (zero-downtime)
#   6. If unhealthy → destroy target → keep active running (no user impact)
#   7. Update state file
#
# Safety:
#   - Old container is kept running for instant rollback
#   - Next deploy naturally cleans up the previously old container
#   - All changes are logged with timestamps
# ═══════════════════════════════════════════════════════════════════════════════

COMPOSE_FILE="docker-compose.prod.yml"
STATE_FILE=".bluegreen.state"
NGINX_ACTIVE_CONF="nginx/active.conf"
MAX_HEALTH_RETRIES=15
HEALTH_INTERVAL=4
GRACE_PERIOD_SECS=15

cd "$(dirname "$0")/.."
DEPLOY_DIR="$(pwd)"

# ── Parse arguments ───────────────────────────────────────────────────────────
NEW_DIGEST="${1:-}"
if [ -z "$NEW_DIGEST" ]; then
    echo "Usage: $0 <image-digest>"
    echo "Example: $0 sha256:abc123..."
    exit 1
fi

# ── Load shared env defaults ─────────────────────────────────────────────────
REGISTRY="${REGISTRY:-docker.io}"
IMAGE_NAME="${IMAGE_NAME:-devidolrun/expenso}"
FULL_IMAGE="${REGISTRY}/${IMAGE_NAME}@${NEW_DIGEST}"

# ── Load current state ────────────────────────────────────────────────────────
ACTIVE_COLOR="blue"
BLUE_DIGEST=""
GREEN_DIGEST=""

if [ -f "$STATE_FILE" ]; then
    # shellcheck source=/dev/null
    source "$STATE_FILE"
fi

if [ "$ACTIVE_COLOR" != "blue" ] && [ "$ACTIVE_COLOR" != "green" ]; then
    echo "WARN: Invalid ACTIVE_COLOR '$ACTIVE_COLOR' in state. Defaulting to blue."
    ACTIVE_COLOR="blue"
fi

# Determine target color (the one that is NOT currently active)
if [ "$ACTIVE_COLOR" = "blue" ]; then
    TARGET_COLOR="green"
else
    TARGET_COLOR="blue"
fi

TARGET_VAR="${TARGET_COLOR^^}_IMAGE"
ACTIVE_VAR="${ACTIVE_COLOR^^}_IMAGE"

echo "════════════════════════════════════════════════════════════════"
echo "  BLUE/GREEN DEPLOYMENT"
echo "  Active: $ACTIVE_COLOR  →  Target: $TARGET_COLOR"
echo "  Image:  $FULL_IMAGE"
echo "  Time:   $(date -Iseconds)"
echo "════════════════════════════════════════════════════════════════"

# ── Step 1: Deploy target container ───────────────────────────────────────────
echo ">>> [1/5] Pulling image for $TARGET_COLOR..."
export "$TARGET_VAR=$FULL_IMAGE"
docker compose -f "$COMPOSE_FILE" pull "app-$TARGET_COLOR"

echo ">>> [2/5] Starting $TARGET_COLOR container..."
docker compose -f "$COMPOSE_FILE" up -d "app-$TARGET_COLOR"

# ── Step 2: Health checks on target ───────────────────────────────────────────
echo ">>> [3/5] Running health checks on $TARGET_COLOR..."
HEALTHY=false
for i in $(seq 1 $MAX_HEALTH_RETRIES); do
    # First: check Docker-native health status
    HEALTH_STATUS=$(docker inspect \
        --format='{{.State.Health.Status}}' \
        "expenso-$TARGET_COLOR" 2>/dev/null || echo "unknown")

    echo ">>>   Attempt $i/$MAX_HEALTH_RETRIES — Docker health: $HEALTH_STATUS"

    if [ "$HEALTH_STATUS" = "healthy" ]; then
        # Second: verify HTTP response from inside the container
        if docker compose -f "$COMPOSE_FILE" exec -T "app-$TARGET_COLOR" \
            sh -c 'wget -qO- http://localhost:3000/api/health' >/dev/null 2>&1; then
            echo ">>>   $TARGET_COLOR passed HTTP health check"
            HEALTHY=true
            break
        fi
    fi

    sleep "$HEALTH_INTERVAL"
done

if [ "$HEALTHY" != "true" ]; then
    echo ""
    echo "ERROR: $TARGET_COLOR failed all health checks."
    echo ">>> Destroying $TARGET_COLOR container..."
    docker compose -f "$COMPOSE_FILE" rm -sf "app-$TARGET_COLOR" || true
    echo ">>> Kept $ACTIVE_COLOR running. NO traffic was switched."
    echo "════════════════════════════════════════════════════════════════"
    echo "  DEPLOYMENT FAILED — Users unaffected"
    echo "════════════════════════════════════════════════════════════════"
    exit 1
fi

# ── Step 3: Switch traffic (zero-downtime nginx reload) ───────────────────────
echo ">>> [4/5] Switching nginx from $ACTIVE_COLOR → $TARGET_COLOR..."
cat > "$NGINX_ACTIVE_CONF" <<EOF
# Auto-generated by deploy-bluegreen.sh at $(date -Iseconds)
# Active backend: $TARGET_COLOR
upstream backend {
    server app-${TARGET_COLOR}:3000;
}
EOF

echo ">>> Reloading nginx gracefully..."
docker compose -f "$COMPOSE_FILE" exec nginx nginx -s reload

# ── Step 4: Grace period for connection drain ─────────────────────────────────
echo ">>> Waiting ${GRACE_PERIOD_SECS}s for connections to drain from $ACTIVE_COLOR..."
sleep "$GRACE_PERIOD_SECS"

# ── Step 5: Stop old container (kept until now for instant rollback) ──────────
echo ">>> [5/5] Stopping previous $ACTIVE_COLOR container..."
docker compose -f "$COMPOSE_FILE" stop "app-$ACTIVE_COLOR" || true
docker compose -f "$COMPOSE_FILE" rm -sf "app-$ACTIVE_COLOR" || true

# ── Update state ──────────────────────────────────────────────────────────────
cat > "$STATE_FILE" <<EOF
# Blue/Green state — managed by deploy-bluegreen.sh
ACTIVE_COLOR=$TARGET_COLOR
BLUE_DIGEST=$([ "$TARGET_COLOR" = "blue" ] && echo "$NEW_DIGEST" || echo "$BLUE_DIGEST")
GREEN_DIGEST=$([ "$TARGET_COLOR" = "green" ] && echo "$NEW_DIGEST" || echo "$GREEN_DIGEST")
LAST_DEPLOY=$(date -Iseconds)
EOF

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  DEPLOYMENT SUCCESSFUL"
echo "  Active color: $TARGET_COLOR"
echo "  Digest:       $NEW_DIGEST"
echo "  Time:         $(date -Iseconds)"
echo "════════════════════════════════════════════════════════════════"
