#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════════════
# Blue/Green Rollback Script
# ═══════════════════════════════════════════════════════════════════════════════
# Usage: ./scripts/rollback-bluegreen.sh
#
# Flow:
#   1. Read current active color from .bluegreen.state
#   2. Determine previous color (the one that is NOT active)
#   3. Ensure previous container is running with its last known digest
#   4. Switch nginx back to previous color
#   5. Update state file
#
# Safety:
#   - If previous container was destroyed, it is recreated from its digest
#   - Rollback is near-instant (nginx reload only)
# ═══════════════════════════════════════════════════════════════════════════════

COMPOSE_FILE="docker-compose.prod.yml"
STATE_FILE=".bluegreen.state"
NGINX_ACTIVE_CONF="nginx/active.conf"

cd "$(dirname "$0")/.."

# ── Load state ────────────────────────────────────────────────────────────────
if [ ! -f "$STATE_FILE" ]; then
    echo "ERROR: State file $STATE_FILE not found. Cannot determine rollback target."
    exit 1
fi

# shellcheck source=/dev/null
source "$STATE_FILE"

if [ "$ACTIVE_COLOR" != "blue" ] && [ "$ACTIVE_COLOR" != "green" ]; then
    echo "ERROR: Invalid ACTIVE_COLOR in state file."
    exit 1
fi

# Determine previous color
if [ "$ACTIVE_COLOR" = "blue" ]; then
    PREVIOUS_COLOR="green"
    PREVIOUS_DIGEST="${GREEN_DIGEST:-}"
else
    PREVIOUS_COLOR="blue"
    PREVIOUS_DIGEST="${BLUE_DIGEST:-}"
fi

if [ -z "$PREVIOUS_DIGEST" ]; then
    echo "ERROR: No digest recorded for $PREVIOUS_COLOR. Cannot rollback."
    exit 1
fi

REGISTRY="${REGISTRY:-docker.io}"
IMAGE_NAME="${IMAGE_NAME:-devidolrun/expenso}"
FULL_IMAGE="${REGISTRY}/${IMAGE_NAME}@${PREVIOUS_DIGEST}"

echo "════════════════════════════════════════════════════════════════"
echo "  BLUE/GREEN ROLLBACK"
echo "  Current active: $ACTIVE_COLOR"
echo "  Rolling back to: $PREVIOUS_COLOR"
echo "  Digest: $PREVIOUS_DIGEST"
echo "  Time:   $(date -Iseconds)"
echo "════════════════════════════════════════════════════════════════"

# ── Ensure previous container is running ──────────────────────────────────────
echo ">>> Ensuring $PREVIOUS_COLOR container is available..."
PREVIOUS_VAR="${PREVIOUS_COLOR^^}_IMAGE"
export "$PREVIOUS_VAR=$FULL_IMAGE"

docker compose -f "$COMPOSE_FILE" up -d "app-$PREVIOUS_COLOR"

# Quick health check on previous container
echo ">>> Waiting for $PREVIOUS_COLOR to become healthy..."
for i in $(seq 1 10); do
    HEALTH_STATUS=$(docker inspect \
        --format='{{.State.Health.Status}}' \
        "expenso-$PREVIOUS_COLOR" 2>/dev/null || echo "unknown")
    echo ">>>   Attempt $i — Docker health: $HEALTH_STATUS"
    if [ "$HEALTH_STATUS" = "healthy" ]; then
        break
    fi
    sleep 3
done

# ── Switch nginx ──────────────────────────────────────────────────────────────
echo ">>> Switching nginx to $PREVIOUS_COLOR..."
cat > "$NGINX_ACTIVE_CONF" <<EOF
# Auto-generated by rollback-bluegreen.sh at $(date -Iseconds)
# Active backend: $PREVIOUS_COLOR
upstream backend {
    server app-${PREVIOUS_COLOR}:3000;
}
EOF

docker compose -f "$COMPOSE_FILE" exec nginx nginx -s reload

# ── Update state ──────────────────────────────────────────────────────────────
cat > "$STATE_FILE" <<EOF
# Blue/Green state — managed by deploy-bluegreen.sh / rollback-bluegreen.sh
ACTIVE_COLOR=$PREVIOUS_COLOR
BLUE_DIGEST=$BLUE_DIGEST
GREEN_DIGEST=$GREEN_DIGEST
LAST_ROLLBACK=$(date -Iseconds)
EOF

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ROLLBACK SUCCESSFUL"
echo "  Active color is now: $PREVIOUS_COLOR"
echo "  Time: $(date -Iseconds)"
echo "════════════════════════════════════════════════════════════════"
