/*
  Warnings:

  - The values [EXPENSE_SOFT_DELETED,ATTACHMENT_REMOVED,CATEGORY_CREATED,CATEGORY_UPDATED,CATEGORY_DELETED,ALLOWED_EMAIL_DELETED] on the enum `AuditAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('USER_ROLE_CHANGED', 'EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_ARCHIVED', 'EXPENSE_RESTORED', 'EXPENSE_SUBMITTED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'EXPENSE_PAID', 'EXPENSE_CANCELLED', 'ATTACHMENT_ADDED', 'ATTACHMENT_ARCHIVED', 'TAG_ASSIGNED', 'TAG_REMOVED', 'TAG_DEACTIVATED', 'SALARY_RECORD_CREATED', 'SALARY_RECORD_UPDATED', 'CREDENTIAL_ENTRY_CREATED', 'CREDENTIAL_ENTRY_UPDATED', 'CREDENTIAL_ENTRY_DISABLED', 'CREDENTIAL_ENTRY_REENABLED', 'ALLOWED_EMAIL_CREATED', 'ALLOWED_EMAIL_UPDATED', 'ALLOWED_EMAIL_DEACTIVATED', 'FUNDENTRYCREATED', 'FUND_ENTRY_ARCHIVED', 'SETTINGS_UPDATED', 'OTHER');
ALTER TABLE "audit_log" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

-- DropIndex
DROP INDEX "expense_fromDate_toDate_idx";

-- AlterTable
ALTER TABLE "exchange_rate_cache" ALTER COLUMN "id" DROP DEFAULT;
